version: "3"

networks:
  docknet:

services:
  agent:
    image: grafana/agent:latest
    container_name: agent
    hostname: agent
    ports:
      - "12345:12345"
    volumes:
    - C:\Projects\docker\conf-agent\agent.yaml:/etc/agent/agent.yaml
    - C:\Projects\Movieapp:/var/log
    command: -config.file=/etc/agent/agent.yaml
 

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    hostname: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
 

  #prometheus:
    #image: prom/prometheus:latest
    #container_name: prometheus
    #hostname: prometheus
    #ports:
    #  - "9090:9090"
    #volumes:
    #- ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #command: 
    #  --web.enable-lifecycle
    #  --config.file=/etc/prometheus/prometheus.yml
    #  --web.enable-remote-write-receiver
    #networks:
    #  - docknet

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
 