apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp-frontend
  labels:
    app: movieapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieapp-frontend
  template:
    metadata:
      name: movieapp-frontend
      labels: 
        app: movieapp-frontend
    spec:
      containers:
        - name: movieapp-frontend
          image: madhan29/movieapp-fe:v1
          ports:
            - containerPort: 3000     
---
apiVersion: v1
kind: Service
metadata:
  name: movieappfe-service
spec:
  type: NodePort
  selector:
    app: movieapp-frontend
  ports:
    - port: 3000
      targetPort: 3000