apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieapp
  template:
    metadata:
      labels:
        app: movieapp
    spec:
      containers:
        - name: movieapp
          image: madhan29/moviebookingapp:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movieapp-service
spec:
  type: NodePort
  selector:
    app: movieapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
