apiVersion: v1
kind: Pod
metadata:
  name: movieapp
  labels:
    app: movieapp
spec:
   containers:
     - name: moviebooking
       image: madhan29/movieapp:v1
       ports:
         - containerPort: 8080
         