modules:
  default:
    headers:
      X-Dummy: my-test-header
    metrics:
    - name: animal_json
      type: object
      help: Example of top-level lists in a separate module
      path: '{ [*] }'
      labels:
        name: '{ .noun }'
        predator: '{ .predator }'
      values:
        population: '{ .population }'